### ISSUE TITLE
importScripts add default url automatically

### ISSUE THREAD

**Issue by Hosar** [goldhand/sw-precache-webpack-plugin#29]
When adding the publicPath to the importScripts section it will generate something like:
`importScripts('http://localhost:3000/otherscript.js')`. But importScripts adds an url by default, so when trying to import I'm getting something like:
`importScripts('http://localhost:3000/http://localhost:3000/otherscript.js')` causing an error.
In **webpack.config** I set:
new swPrecacheWebpackPlugin({
  importScripts:['someScript-[hash].js']
})

Is this expected? because now I'm getting an error because import scripts can not find
`http://localhost:3000/http://localhost:3000/otherscript.js`

Should I set the script in a different way in webpack?

**Comment by goldhand** [comment]
Hey @Hosar this behavior was added here: https://github.com/goldhand/sw-precache-webpack-plugin/commit/1b79e98a81090cf4f2b87096f176fc620688904a

I like it personally, if you have a `publicPath` already defined in your webpack config, we should use that to correct the URI for the import scripts. We also do that for the regular assets using the `replacePrefix` option https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/src/index.js#L80

What are your thoughts? It sounds like you are defining the `publicPath` in the importScripts config value right? Or is it being added twice now?

**Comment by Hosar** [comment]
Hey, glad you are back @goldhand !
I have the following configuration, but now I'm getting an error because importScripts is trying to load from `importScripts('http://localhost:3000/http://localhost:3000/script_sw.js')`, do I need add or remove something on my config?, it's because I'm on localhost?

```
new swPrecacheWebpackPlugin(
      {
        cacheId: 'cacheName',
        filename: 'swPrecache.js',
        staticFileGlobsIgnorePatterns: SERVICE_WORKER_IGNORE_PATTERNS,
        maximumFileSizeToCacheInBytes: 4194304,
        importScripts:['/dist/script_sw-[hash].js']
      }
    )
  ]
```

**Comment by goldhand** [comment]
The config looks good to me. In your webpack plugin, do you have a publicPath defined as `'http://localhost:3000`? I will need to look more into this because it shouldn't be duplicating.

**Comment by goldhand** [comment]
@Hosar maybe this is fixed in https://github.com/goldhand/sw-precache-webpack-plugin/commit/4443652ea2da850366191c28f12dcf3cfbf9bdcd?

Please confirm when you have a chance

**Comment by Hosar** [comment]
Still getting an error. See attached img.
![importscriptserror](https://cloud.githubusercontent.com/assets/9598455/20946334/e78ec5b4-bbcf-11e6-9a1b-b878563e4f34.png)

**Comment by goldhand** [comment]
Hmmmm. Weird.
I wonder why it does `/dist/dist/` too?

**Comment by goldhand** [comment]
@Hosar is this still an issue? I've never been able to replicate it.

**Comment by Hosar** [comment]
No it's not an issue. Thank you!
